---
- name: move sshd_config
  copy:
    dest: /etc/ssh/sshd_config
    src: sshd_config

- name: add jump binary
  copy:
    dest: /usr/bin/jump
    src: jump_aarch64
    mode: 0755
  
- name: add jump service
  copy:
    dest: /etc/systemd/system/jump.service
    src: jump.service

- name: enable jump service
  systemd:
    name: jump.service
    enabled: true
