- name: configure main switch interface
  template:
    src: main.network.j2
    dest: /etc/systemd/network/eth0.network

- name: install vlan interfaces
  template:
    src: vlan.netdev.j2
    dest: "/etc/systemd/network/switch.{{ item }}.netdev"
  loop: "{{switch_vlans}}"

- name: configure vlan interfaces
  template:
    src: vlan.network.j2
    dest: "/etc/systemd/network/switch.{{ item }}.network"
  loop: "{{switch_vlans}}"